-- Bootstrap OLTP schema on PORTFOLIO_ATP (run as ADMIN, then OLTP_SHOP)
-- See: docs/oci-portfolio/01-enterprise-dwh-oci-data-integration.md

ALTER SESSION SET CURRENT_SCHEMA = oltp_shop;

CREATE TABLE customers (
    customer_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR2(200) NOT NULL,
    email            VARCHAR2(200),
    city             VARCHAR2(100),
    country          VARCHAR2(2) DEFAULT 'BR',
    status           VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE products (
    product_id       VARCHAR2(32) PRIMARY KEY,
    product_name     VARCHAR2(200) NOT NULL,
    category         VARCHAR2(100),
    unit_price       NUMBER(12,2) NOT NULL,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE orders (
    order_id         VARCHAR2(32) PRIMARY KEY,
    customer_id      NUMBER NOT NULL REFERENCES customers(customer_id),
    order_date       DATE NOT NULL,
    status           VARCHAR2(20) DEFAULT 'COMPLETED',
    last_updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE order_items (
    order_item_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         VARCHAR2(32) NOT NULL REFERENCES orders(order_id),
    product_id       VARCHAR2(32) NOT NULL REFERENCES products(product_id),
    quantity         NUMBER NOT NULL,
    unit_price       NUMBER(12,2) NOT NULL,
    last_updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX ix_orders_customer ON orders(customer_id);
CREATE INDEX ix_orders_date ON orders(order_date);
CREATE INDEX ix_orders_updated ON orders(last_updated_at);
CREATE INDEX ix_items_order ON order_items(order_id);
CREATE INDEX ix_items_updated ON order_items(last_updated_at);

-- Seed data
INSERT INTO customers (full_name, email, city) VALUES ('Ana Silva', 'ana@email.com', 'São Paulo');
INSERT INTO customers (full_name, email, city) VALUES ('Bruno Costa', 'bruno@email.com', 'Rio de Janeiro');
INSERT INTO customers (full_name, email, city) VALUES ('Carla Mendes', 'carla@email.com', 'Curitiba');
COMMIT;

INSERT INTO products VALUES ('P001', 'Wireless Mouse', 'Electronics', 89.90, SYSTIMESTAMP);
INSERT INTO products VALUES ('P002', 'USB-C Hub', 'Electronics', 149.90, SYSTIMESTAMP);
INSERT INTO products VALUES ('P003', 'Notebook Stand', 'Office', 199.00, SYSTIMESTAMP);
COMMIT;

INSERT INTO orders VALUES ('O1001', 1, DATE '2026-05-01', 'COMPLETED', SYSTIMESTAMP);
INSERT INTO orders VALUES ('O1002', 2, DATE '2026-05-02', 'COMPLETED', SYSTIMESTAMP);
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES ('O1001', 'P001', 2, 89.90);
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES ('O1002', 'P003', 1, 199.00);
COMMIT;
