-- DWH star schema on PORTFOLIO_ADW (run as DWH user)
-- See: docs/oci-portfolio/01-enterprise-dwh-oci-data-integration.md

CREATE TABLE d_date (
    date_key        NUMBER PRIMARY KEY,
    full_date       DATE NOT NULL,
    year_num        NUMBER(4),
    month_num       NUMBER(2),
    day_num         NUMBER(2),
    quarter_num     NUMBER(1),
    month_name      VARCHAR2(20)
);

CREATE TABLE d_customer (
    customer_key    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     NUMBER NOT NULL,
    full_name       VARCHAR2(200),
    email           VARCHAR2(200),
    city            VARCHAR2(100),
    country         VARCHAR2(2),
    status          VARCHAR2(20),
    effective_from  DATE NOT NULL,
    effective_to    DATE DEFAULT DATE '9999-12-31',
    is_current      CHAR(1) DEFAULT 'Y'
);

CREATE TABLE d_product (
    product_key     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      VARCHAR2(32) NOT NULL,
    product_name    VARCHAR2(200),
    category        VARCHAR2(100),
    unit_price      NUMBER(12,2)
);

CREATE TABLE f_sales (
    sales_key       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key        NUMBER NOT NULL,
    customer_key    NUMBER NOT NULL,
    product_key     NUMBER NOT NULL,
    order_id        VARCHAR2(32),
    quantity        NUMBER,
    unit_price      NUMBER(12,2),
    revenue         NUMBER(14,2),
    batch_id        VARCHAR2(50),
    loaded_at       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX ix_f_sales_date ON f_sales(date_key);
CREATE INDEX ix_f_sales_customer ON f_sales(customer_key);

INSERT INTO d_date
SELECT TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')),
       d,
       EXTRACT(YEAR FROM d),
       EXTRACT(MONTH FROM d),
       EXTRACT(DAY FROM d),
       TO_NUMBER(TO_CHAR(d, 'Q')),
       TRIM(TO_CHAR(d, 'Month'))
FROM (
  SELECT DATE '2020-01-01' + LEVEL - 1 AS d
  FROM dual
  CONNECT BY LEVEL <= 3653
);
COMMIT;
